server.port: 9000
spring:
  application:
    name: dding-board-article-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/article
    username: root
    password: 1001
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: false
    properties:
      hibernate.dialect: org.hibernate.dialect.MySQL8Dialect